### ISSUE TITLE
Non-Deterministic Addition

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/solver-rewards#191]
Dune's SparkSQL appears to have an unreliable non-deterministic result when summing "string" integers.

Originally discovered by @fleupold and summarized very well by this [simple query](https://dune.com/queries/1992539)

I am quit confident that this error is coming from the lack of guaranteed ordering with UNION ALL

Here is a [Fixed Fork of above](https://dune.com/queries/1995403) that always returns the same results.

If `X = MAX_INT` and we are working with the unordered set `{X-1, -X, 1}` we find that one ordering of the numbers will overflow in the first sum while the other ordering causes the overflow not to happen...

(X - 1) -X = 0  ---> then adding 1 yields 1

while 

1 - X = 1 - X ----> Then adding (X - 1) yields 0

See screenshot

<img width="922" alt="Screenshot 2023-02-13 at 11 01 00" src="https://user-images.githubusercontent.com/11778116/218432314-33deb16d-6077-479b-9932-cb2d8cff13cc.png">

So, it appears we fix the non-deterministic results (on overflows) but ordering our tables. However, its it unclear which ordering we actually want in our case.

cc @fleupold

**Comment by fleupold** [comment]
Very nice find!

My idea was to remove the `having abs(sum(amount)) > 0.0001` (which I believe is pointless because amounts are wei and therefore always > 1) and `having sum(amount) != 0` as this would at least fix the consequence of the inconsistency that we sometimes don't even try to fetch prices for tokens that we should, but it may increase the execution time (haven't tested it).

The results would still be non-deterministic but the impact should be tiny (in the scale of the precision loss and not multiple $100).

But I like a deterministic query better!
